### ISSUE TITLE
Error: Could not display page 

### ISSUE THREAD

**Issue by H0neyBadger** [FIX94/nnu-patcher#1]
Hello,
When I try to connect, I get the following error:

```
Error Code: 111-1056
Could not display page
```

![error111-1056](https://cloud.githubusercontent.com/assets/7838259/10268696/0e1fcdc4-6ac1-11e5-804a-0defcd9872db.jpg)

(wiiu 5.3.2 E) as you can see, this is the European version.
Furthermore, I use a proxy to filter the Nintendo update service.
Do you know if this "patch" works for European e-shop?

Thank you very much for your work!

**Comment by FIX94** [comment]
your "proxy" is wrong then, it has been verified by many that it does work just fine as long as you have the version.bin updated with the installer.

**Comment by carnage702** [comment]
you sure that you dont have e shop blocked on your settings? either with opendns,ccproxy or just router blocking?

**Comment by H0neyBadger** [comment]
I feel silly,
I forgot this rule in my config

```
.wup.shop.nintendo.net
```

```
1443980774.809     31 192.168.0.100 TCP_DENIED/403 1509 CONNECT ninja.wup.shop.nintendo.net:443 - NONE/- text/html
```

Thanks, everyone.

**Comment by EpicLPer** [comment]
Just as a side note but isn't it better to ask these things on GBAtemp rather than here as a bug report? :)

**Comment by H0neyBadger** [comment]
Yes, I agree.
Sorry for the inconvenience.
